runtime: custom
env: flex
service: maruthi-testing

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  name: "projects/maruti-project-454712/global/networks/maruthi-vpc"
  subnetwork_name: "subnet1"
