steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/maruti-project-454712/test/web-ui', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/maruti-project-454712/test/web-ui']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']

images:
  - 'asia-south1-docker.pkg.dev/maruti-project-454712/test/web-ui'

options:
  logging: CLOUD_LOGGING_ONLY
