name: Deploy to GCP VM

on:
  push:
    branches:
      - maruthi-preliv

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.MARUTHI_SSH_PRIVATE_KEY_MAIN }}

      - name: Sync files to remote server using rsync
        env:
          GCP_VM_USERNAME: ${{ secrets.MARUTHI_GCP_VM_USERNAME_MAIN }}
          GCP_VM_IP: ${{ secrets.MARUTHI_GCP_VM_IP_MAIN }}
        run: |
          rsync -avz --exclude='.git/' --exclude='.github/' --exclude='node_modules/' --include='.*' --include='*' --prune-empty-dirs -e "ssh -vvv -o StrictHostKeyChecking=no" ./ ${{ secrets.MARUTHI_GCP_VM_USERNAME_MAIN }}@${{ secrets.MARUTHI_GCP_VM_IP_MAIN }}:/nginx-docker/
      - name: SSH into the server and deploy with Docker Compose
        env:
          GCP_VM_USERNAME: ${{ secrets.MARUTHI_GCP_VM_USERNAME_MAIN }}
          GCP_VM_IP: ${{ secrets.MARUTHI_GCP_VM_IP_MAIN }}
        run: |
          ssh -o StrictHostKeyChecking=no $GCP_VM_USERNAME@$GCP_VM_IP << 'EOF'
            set -e
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            echo "Timestamp: $TIMESTAMP"
            cd /nginx-docker/
            docker system prune -af
            docker compose up -d
            echo "Creating GCP compute image with unique identifier..."
            gcloud compute images create ig-task-image-${TIMESTAMP} \
            --source-disk=ig-task \
            --source-disk-zone=us-central1-c \
            --family=ig-task-family \
            --force
            gcloud compute instance-templates create ig-task-template-${TIMESTAMP} \
            --machine-type=e2-micro \
            --image-family=ig-task-family \
            --image-project=${{ secrets.GCP_PROJECT_ID }} \
            --tags=http-server,https-server,ig-task \
            --boot-disk-size=10GB \
            --boot-disk-type=pd-balanced
            gcloud compute instance-groups managed rolling-action start-update ig-task-group  \
            --version=template=ig-task-template-${TIMESTAMP} \
            --zone=us-central1-c \
            --type=proactive
          EOF
