name: Build and Deploy CMS to MIG

on:
  push:
    branches:
      - maruthi-prelive

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: maruti-project-454712 
      REGION: asia-south1
      REPO_NAME: ig-task
      IMAGE_NAME: sample-test
      MIG_NAME: instance-group-github
      HOST_PROJECT: maruti-project
      NETWORK_NAME: maruthi-vpc
      SUBNET_NAME: subnet1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate using service account key
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'  # Use the service account key stored in GitHub Secrets

      - name: Set up Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build and Push Docker Image to Artifact Registry
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$TIMESTAMP"
          TEMPLATE_NAME="ig-group-github-${TIMESTAMP}"
          echo "Building Docker image..."
          docker build -t $IMAGE_URI .
          echo "Pushing Docker image to Artifact Registry..."
          docker push $IMAGE_URI
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          echo "TEMPLATE_NAME=$TEMPLATE_NAME" >> $GITHUB_ENV

      - name: Create instance template from Docker image
        run: |
          echo "Creating instance template: $TEMPLATE_NAME"
          gcloud compute instance-templates create-with-container $TEMPLATE_NAME \
            --project=${{ env.PROJECT_ID }} \
            --region=${{ env.REGION }} \
            --machine-type=e2-micro \
            --boot-disk-type=pd-balanced \
            --boot-disk-size=10GB \
            --no-address \
            --network=projects/${{ env.HOST_PROJECT }}/global/networks/${{ env.NETWORK_NAME }}
            --subnet=projects/${{ env.HOST_PROJECT }}/regions/${{ env.REGION }}/subnetworks/${{ env.SUBNET_NAME }} \
            --container-image=$IMAGE_URI \
            --container-restart-policy=always \
            --tags=instance-github 

      - name: Rolling update on regional MIG
        run: |
          echo "Starting rolling update on MIG: ${{ env.MIG_NAME }} using template: $TEMPLATE_NAME"
          gcloud compute instance-groups managed rolling-action start-update ${{ env.MIG_NAME }} \
            --project=${{ env.PROJECT_ID }} \
            --region=${{ env.REGION }} \
            --version template=$TEMPLATE_NAME \
            --max-surge=3 \
            --max-unavailable=0
